spring.application.name=TECHCUP

# Logging
logging.level.root=WARN
logging.level.edu.dosw.TECHCUP=DEBUG
logging.pattern.console=%d{HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.file.name=logs/techcup.log