spring.application.name=TECHCUP

PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/techcup
spring.datasource.username=postgres
spring.datasource.password=Juanes2004
spring.datasource.driver-class-name=org.postgresql.Driver

JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

jwt.secret=dGVjaGN1cC1zZWNyZXQta2V5LXBhcmEtand0LWF1dGhlbnRpY2F0aW9uLTI1NmJpdHM=

jwt.expiration=3600000