spring.application.name=TECHCUP

#PostgreSQL
spring.datasource.url=${TECHCUP_DATASOURCE_URL:jdbc:postgresql://metro.proxy.rlwy.net:36178/railway}
spring.datasource.username=${TECHCUP_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${TECHCUP_DATASOURCE_PASSWORD:RwwtYZauPffZDChxCIeaBhMWFGoQZdhX}
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

#Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# JWT
jwt.secret=${JWT_SECRET:dGVjaGN1cC1zZWNyZXQta2V5LXBhcmEtand0LWF1dGhlbnRpY2F0aW9uLTI1NmJpdHM=}
jwt.expiration=${JWT_EXPIRATION:3600000}

# CORS
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}

# OAuth2 Google
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile
